### ISSUE TITLE
missing package.json and some declarations

### ISSUE THREAD

**Issue by Miky88** [Poker1st/ModMail#5]
title says everything

**Comment by Cyber-Pop** [comment]
just do npm init -y and it'll make a package.json and make sure that you have installed other deps

**Comment by Miky88** [comment]
that's not how it works, of you don't include package.json I'll need to
install deps manually and that's such annoying :)

Il sab 17 ott 2020, 07:25 CyberPop <notifications@github.com> ha scritto:
